### ISSUE TITLE
Crash parsing my region files

### ISSUE THREAD

**Issue by lf-** [owengage/fastnbt#1]
https://github.com/owengage/fastnbt/blob/000b4d16db34d8e4ab410d8c17c129c9f0947247/fastnbt/src/anvil/draw.rs#L43

I am getting an *odd* crash (see below) implying that there are blocks at >256.

Here is [what I believe to be] the offending region file:
[r.1.-2.mca.gz](https://github.com/owengage/fastnbt/files/4916115/r.1.-2.mca.gz)

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 16 but the index is 31', fastnbt/src/anvil/draw.rs:43:23
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:69
  14: fastnbt::anvil::draw::Chunk::id_of
  15: <anvil::RegionBlockDrawer<P> as fastnbt::anvil::draw::RegionDrawer>::draw
  16: fastnbt::anvil::draw::parse_region
  17: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
  18: rayon::iter::plumbing::Folder::consume_iter
  19: rayon::iter::plumbing::bridge_producer_consumer::helper
  20: rayon_core::registry::in_worker
  21: rayon::iter::plumbing::bridge_producer_consumer::helper
  22: rayon_core::job::StackJob<L,F,R>::run_inline
  23: rayon_core::registry::in_worker
  24: rayon::iter::plumbing::bridge_producer_consumer::helper
  25: rayon_core::registry::in_worker
  26: rayon::iter::plumbing::bridge_producer_consumer::helper
  27: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  28: rayon_core::registry::WorkerThread::wait_until_cold
  29: rayon_core::join::join_recover_from_panic
  30: rayon_core::registry::in_worker
  31: rayon::iter::plumbing::bridge_producer_consumer::helper
  32: rayon_core::registry::in_worker
  33: rayon::iter::plumbing::bridge_producer_consumer::helper
  34: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  35: rayon_core::registry::WorkerThread::wait_until_cold
  36: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lf-** [comment]
This is a 1.16 world though I don't think they messed with the world format since a long time ago?

**Comment by lf-** [comment]
The backup right prior to 1.16 upgrade seems to not have this issue. So it appears to be likely caused by something changed in 1.16 re: map format. Super weird.

**Comment by lf-** [comment]
https://github.com/owengage/fastnbt/blob/master/fastnbt/src/anvil/bits.rs#L11

me: 🤡

well this might be the problem. Carry on!

**Comment by owengage** [comment]
Hi there, thanks for trying this out. I haven't got around to testing this with 1.16. Unfortunately it looks like it's not just the blockstates encoding that has changed in 1.16 (which by itself shouldn't be too hard), it also looks like the way I form the 'palette' to draw the world with has broken as well.

I'll update here when I get some spare time to look at it!

**Comment by owengage** [comment]
`master` should now support 1.16 worlds. If you try it out make sure to re-do the palette with an unpacked 1.16 JAR, I won't be supporting 1.15 JARs from here on out.

Let me know if you still run into issues rendering the overworld on 1.16.

**Comment by owengage** [comment]
For a bit more technical information, I now detect if the blockstate and heightmaps are 'tightly' packed and switch which decoding method I use: https://github.com/owengage/fastnbt/blob/master/fastnbt/src/anvil/bits.rs#L11-L67

Basically 1.16 simplified the way they store the blocks at the expense of a little more space to store them.
